### PR TITLE
Fixes for Path.Combine for "file://" prefix and ToolVersion attribute in csproj files.

### PR DESCRIPTION
**Pull request by BlackCentipede**
Reason for ToolVersion modification:
http://unix.stackexchange.com/questions/119701/how-to-open-visual-studio-2013-solution-in-monodevelop

"File://" & "File:" prefix fixes are corrected.

Note: This is still not a working copy for Mono Environment yet.

### CODE REVIEW

**Comment by tony-dinucci** [comment]
I've got to go out for a while.  Will merge this and test on Windows tonight.  Thanks

**Comment by BlackCentipede** [comment]
No problem and you're welcome. :smiley:

**Comment by tony-dinucci** [comment]
I'm having some problems with the merge here I'm afraid.  It's mainly due to the different code formatting you have to me. Pretty much every .cs file line is being seen as a change because of indentation differences between the two of us 

I've spend some time working through it and can see what you've been doing but I can't easily do the merge.

We can do a couple of things here:

1. You're project file changes are fine (no differences with indentation, etc.  If you can just make a pull request with these alone I can merge them straight in - so at least can open with Mono straight away.

* I can just copy your .cs file changes (rather than merge files) - however if I do this obviously you won't be seen as the contributer.  I'm guessing you'd prefer to make the checkin yourself but in order for this to happen we'll have to have consistent coding conventions - so you'd have to revert to original code, leaving majority of file in format it's in and then redo you changes.  

How's this sound?

**Comment by BlackCentipede** [comment]
I'll re-do the pull request and have it up again. By the way, thank you for putting up the dev wiki page.

**Comment by tony-dinucci** [comment]
Thanks mate.  Np about the Wiki page.  I hope you're OK with it all, I know what it's like having to adjust to other people's coding styles.  If there's anything you really don't agree with let me know.

**Comment by BlackCentipede** [comment]
Please close this PullRequest and use the new pull request from me. :)

**Pull request closed without merging**
